export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const USERNAME_UPDATED = 'USERNAME_UPDATED'
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED'